### ISSUE TITLE
Interface vs. Classes (again!)

### ISSUE THREAD

**Issue by khenidak** [Azure/adl#19]
This is meant for weekend deep thinking topic. Here is why I think interfaces are still not a great idea. We still have time to make the best decision possible:

Here is an example
```TypeScript
interface VM {
  Name : string;
}
```

The above is clear, easy to understand right? Yes

Now let us do this

```TypeScript
Interface VM{
 name : string &
 Required &
 LenValidator(10,50);
}
```

The above is still readable. However from a `type` standpoint, this is not a string. It is a `string` and `Required` and `LenValidator`. It is not that we are changing the behavior of `name` we are changing what `name` means. From a runtime perspective this is not the best, here is why:
1. Slow validation, defaulting execution.  
The validation and defauling logic will do the following
-  walk the root object
- For every property, enumerate all validation and defaulting descriptors
- for every descriptor call a well known interface with root object, leveled, and property value. So 
```TypeScript
VM {
 Network: {
  <<snip>>
 // this is defined with validation MinLength(1)
 Interfaces: [IF1{...}, IF2{...}, IF3{...}],
}
```
The call to validate interfaces, will go out with Validate(VMinstance, NetworkIntances, "Interfaces",<Array>)
 

Now, with intersecting types There is no way to enumerate all validation attached to a property. The code will have to look like this
```TypeScript
foreach(validation in validationCatalog){
 if(currentProperty has validation)
   {
    runValidation...
   } 
}
```
in other words, every property on a type will have to be checked against the entire catalog of validation and defaulting functions to check _if it is any of them or not_. As you can tell, this won't be performing.

2. Between `v1` and `v2`, let us say validation or defaulting logic has changed for `VM.name`. The types are no longer comparable, because

```TypeScript
interface vm{
<<snip>>
name : string & Required & MinLen(10)
}
```
does not equal

```TypeScript
interface vm{
<<snip>>
name : string & Required & LenValidate(10,20)
}
```

They are essentially two different types.

3. I understand the need to express `oneOf` and so on. This can be achieved by type aliasing (classic typedef style approach). Here is how (VM OS disk can be from market place, a vhd etc)

```TypeScript
class vhd {
<<describe vhd disk>>
} 

class marketPlaceDisk{
<<describe marketplace disk>>
}

type VMStorage = vhd | marketPlaceDisk;

class VM{
@Requird
storage : VMStorage;
}
```

Can we talk about interfaces vs classes again?

**Comment by fearthecowboy** [comment]
That doesn't change anything; you still have the same amount of validation attached to a property.
The whole point here is to keep as close as possible to describing types using the existing TS type system.  

Utility types ( ie `Required<T>`, `Readonly<T>`, `NonNullable<T>`) already exist in Typescript as a means to facilitate common type transformations. Extending the same pattern to include additional validation is a natural complement to the existing language design.
Introducing a orthogonal means (via decorators) to apply additional type constraints defeats the purpose of using typescript in the first place.  

Furthermore, the constraints of a property should be entirely encapsulated in it's type definition.  That's literally the definition of the type.  

``` ts
value?: number; // either a number or undefined
foo: number;  // is required to be a number
name: string;  // a non-nullable string

// there already is a form of value restriction built into typescript -- the constant choices / enums are the means to expression validation constraints
color: 'red'|'green'|'blue';  a choice of one of several values. Semantically identical to using an enum to constrain the possible values.

// taking that to the next step with additional utility types is a natural extension of the language. 
age: Range<number, 18,65>

drinkingAge: Minimum<integer, 21>

// you can declare MyValidation somewhere, and have code tied to that to perform the validation itself.  all we really would need to do up front is declare the pattern for how to declare arbitrary validators.

arbitrary: string & MyValidation; 
```

The literal definition of interfaces from the TS manual:
> "One of TypeScript’s core principles is that type checking focuses on the shape that values have. In TypeScript, interfaces fill the role of naming these types, and are a powerful way of defining contracts within your code as well as contracts with code outside of your project."

Interfaces describe shapes of things that you can expose. Classes are means to bind functionality together. 

More to the point, if constructed correctly, the TS code is not only still semantically logical TS code, it can still produce valid, runnable artifacts. 



``` ts
/*
 * Virtual Disk
 */
export interface VirtualDisk {
  /**
   * File format.
   */
  format?: string;

  /**
     * size of the disk
     * of which the validation is version dependent
     */
  size:
  (Version<'2019-01-01'> & number) |
  (Version<'2020-02-02'> & number & Minimum<1024>);

  /**
   * name of the disk
   */
  name: string & Pattern<'happy'>;
}

/**
 * Virtual Machine 
 */
export interface VirtualMachine {
  /**
   * Disk for the VM
   */
  disk: VirtualDisk;
}

```

I can describe the full suite of JSON Schema validation using the patterns here. 

And, I'm pretty sure we can construct actual valid code for runtime type guards in the language :

``` ts
let foo: string & Pattern<'happy'>;
let sample  = 'goop';

if( ValidatePatern(sample, 'hello') ) {
  foo = sample; // won't run, because the pattern didn't validate.
}

function ValidatePatern<T>(value: any, p: T): value is Pattern<T> {
  return  value === p || value in p;
}

```
