### ISSUE TITLE
Tightening documentation sugar

### ISSUE THREAD

**Issue by nguerrera** [Azure/adl#202]
## Background

We have debated special syntax for documentation vs. documentation-as-decorators. On the one hand, treating description as just another decorator keeps the language small and simple, and makes it easy for consumers/extenders, but we struggled with the aesthetics and authoring experience.  We've made some progress to make the authoring experience and readability of description decorators more pleasant, but I think we've added too much complexity. A proposal will follow on trying to undo some of the complexity while retaining concise forms. But first a recap of what we have now.

Before any of the recent experiments, we had this:

```
@description("A motor vehicle with four wheels")
model Car {
   @description("The thing that makes the car go.
The description could continue on another line, but the 
indentation has to be out of whack like this.")
   engine: Engine;

  @description("The color of the exterior paint")
  color: Color;

  @description("The suggested retail price")
  price: number;
}
```

Things we didn't like:
1. When you need multiple lines, you want to indent them naturally, but can't.
1. `@description` is long and repetitive, it is going to be on roughly half the lines of code in common case of every property/operation documented and most descriptions being single line!

### (A) Long strings
The first problem (messy multi-line strings) was addressed by introducing another string literal form with inspiration from Swift:

- surrounded by three quote delimeters instead of one. 
- there must be a newline after the opening delimeter and before the closing delimeter.
- The indentation before the closing delimeters is trimmed from all lines.

(The formal rules are a bit more complicated and need to be written down, but not relevant to this issue.)

```
@description("A motor vehicle with four wheels")
model Car {
  @description(
  """
  The thing that makes the car go.
  Now I can indent more naturally but `@description` and parens are still ugly.
  """)
  engine: Engine;
}
```

### (B) description sugar

The second problem (`@description` everywhere) was addressed by treating a leading `"string literal"` the same as a `@description("string literal")`

```
"""
A motor vehicle with four wheels.
""" 
model Car {
   """
   The thing that makes the car go.
   """
   engine: Engine;
}
```

With that change, you could also use "single line string" for models and operations, but not for properties because that there's a conflict with quoted property names and description sugar.

```
model Car  {
   "If this is allowed" color: Color;
   // then this will not parse as we want"
   "engine-type": EngineType;
}
```

### (C) Trailing description sugar

With the above, we're still burning at least 3 extra lines per property at a minimum for descriptions. Without a good leading single-line form, we allowed single-line documentation strings to trail properties:

```
"Vehicle with four wheels"
model Car {
   engine: Engine   "The things that makes the car go";
   color: Color     "The color of the exterior paint.";
}
```

Now you can have no added lines for properties and 1 added line for models and interfaces with short descriptions. However, the language is veering into strange territory here. While it looks kind of like how you might comment `// comment` a property naturally, which is where the idea came from, it just doesn't feel right to put actual (non-trivia) syntax there. The positioning of the semicolon after the description is particularly jarring. 

### (D) Single decorator arg without parens

Another problem that still remains with above is that while you get a nicer syntax for description, you're still left with unisghtly parens for your custom decorators

```
@fancyDescription("""
Almost back to where we started for any other decorator
(Long strings still help with indentation)
""")
model M  {}
```

To solve this, we made the parens optional when a decorator takes a single literal arg

```
@fancyDescription 
"""
This looks closer to a standard description 
"""
model M {
   // can also use this for bools and numbers
   @hidden true
   @fieldNum 1
   x: string;
}
```

## Proposal

I propose the following changes.

1. Remove B (description sugar).
2. Remove C (trailing description sugar). 
3. Keep A (long strings)
4. Keep C (single arg without parens)
5. Introduce `@_` as alias for `@description`

This makes the language much simpler:

* `@_` is only a trivial addition to the standard library. The core language knows nothing special about description vs. any other decorator.
* The only distinction between long and short strings is made during scanning. Parsing can treat long and short string literals the same way in every position.

Here is a real example from app-config this language simplification:

```
@_ """
Azure App Configuration error object.

Using multiple lines for illustration here, but could be on one line like properties.
Properties could be multi-line like this too.
"""
model Error {
  @_ "The type of the error"
  type: string;

  @_ "A brief summary of the error.";
  title: string;         

  @_ "The name of the parameter that resulted in the error."
  name: string

  @_ "A detailed description of the error.";
  detail: string  

  @_ "The HTTP status code that the error maps to."     
  statusCode: int32
}
```

And with more decoration:

````
@_ """
Azure App Configuration error object.
Yada, yada, yada
"""
@example """
{
  "type": "Critical",
  "title": "Some title",
  "name": "Some name",
  "statusCode: 500
}
"""
model Error {
  @_ "The type of the error"
  @fieldNum 1
  type: string;

  @_ "A brief summary of the error."
  @fieldNum 2
  title: string;         

  @_ "The name of the parameter that resulted in the error."
  @fieldNum 3
  name: string;

  @_ "A detailed description of the error."
  @fieldNum 4
  detail: string;

  @_ "The HTTP status code that the error maps to." 
  @fieldNum 5
  statusCode: int32;
}
````

### Side note
`@example` above shows another couple of interesting things. 

1. Unlike javadoc or C# xml docs, or swift markdown docs, we can put documentation other than the description in their own decorators rather than in another language embedded in a comment. You can end up with something that looks a lot like javadoc without the "/**" and "*/". That said, it's also possible to embed such a language in a decorator...

2. It begs for ` """ json` a la markdown so that we can syntax highlight different formats embedded in decorators.  I will leave that for a separate proposal. 😃

### Alternative
If `@_` is taking it too far, maybe just a shorter name like `@desc` or `@doc`.

````
@doc """
Azure App Configuration error object.
Yada, yada, yada
"""
@example """
{
  "type": "Critical",
  "title": "Some title",
  "name": "Some name",
  "statusCode: 500
}
"""
model Error {
  @doc "The type of the error"
  @fieldNum 1
  type: string;

  @doc "A brief summary of the error."
  @fieldNum 2
  title: string;         

  @doc "The name of the parameter that resulted in the error."
  @fieldNum 3
  name: string;

  @doc "A detailed description of the error."
  @fieldNum 4
  detail: string;

  @doc "The HTTP status code that the error maps to." 
  @fieldNum 5
  statusCode: int32;
}
````

**Comment by nguerrera** [comment]
Didn't mean to submit, still writing this up

**Comment by nguerrera** [comment]
Also might be worth looking at this with alternate `[]` decorator syntax, which is still allowed at this point in time.

````
[_ """
Azure App Configuration error object.
Yada, yada, yada
"""]
@example ```
{
  "type": "Critical",
  "title": "Some title",
  "name": "Some name",
  "statusCode: 500;
}
```
model Error {
  [_ "The type of the error"]
  [fieldNum 1]
  type: string;

  [_ "A brief summary of the error."]
  [fieldNum 2]
  title: string;         

  [_ "The name of the parameter that resulted in the error."]
  [fieldNum 3]
  name: string;

  [_ "A detailed description of the error."]
  [fieldNum 4]
  detail: string;

  [_ "The HTTP status code that the error maps to.] 
  [fieldNum 5]
  statusCode: int32;
}
````

**Comment by nguerrera** [comment]
Or alternate syntax with parens:


[_("""
  Azure App Configuration error object.
  Yada, yada, yada
  """)]
@example ```
{
  "type": "Critical",
  "title": "Some title",
  "name": "Some name",
  "statusCode: 500;
}
```
model Error {
  [_("The type of the error")]
  [fieldNum(1)]
  type: string;

  [_ ("A brief summary of the error.")]
  [fieldNum(2)]
  title: string;         

  [_ ("The name of the parameter that resulted in the error.")]
  [fieldNum(3)]
  name: string;

  [_("A detailed description of the error.")]
  [fieldNum(4)]
  detail: string;

  [_("The HTTP status code that the error maps to."] 
  [fieldNum(5)]
  statusCode: int32;
}
````

**Comment by nguerrera** [comment]
Decision from design discussion: go forward with alternative proposal: `@doc` not `@_`

**Comment by nguerrera** [comment]
@bterlson @daviwil It's come up a few times that we might have oversimplified in getting rid of (B) above, which let you write:
```
"""
My documentation here
""" 
model M {}
```

with an implicit doc. With the change, you now have to write:
```
@doc """
My documentation here
""" 
model M {}
```

I think the main rationale for that removal in my view was this: 

> This makes the language much simpler:
>
> `@doc`  is only a trivial addition to the standard library. The core language knows nothing special about description vs. any other decorator.
>The only distinction between long and short strings is made during scanning. Parsing can treat long and short string literals the same way in every position.

I find it simplified the code considerably and makes it easier to understand and I think easier to explain. We can decide to eat back this complexity if we really want the aesthetics and ergonomics back. I don't personally think we should go back, but I also don't feel very strong about it. 😆

**Comment by nguerrera** [comment]
Reopening the issue to track any change here.

**Comment by bterlson** [comment]
If we want to keep the complexity where its at, could we choose to drop the parenless decorators and reinstate the decoratorless doc? Not arguing for it yet, just stewing...

**Comment by nguerrera** [comment]
I think I'd like to keep parenless either way for things like `@example` above. Things that are generally multi-line but also not `@doc`. 

But maybe this is OK.

```
@example("""
{
  "type": "Critical",
  "title": "Some title",
  "name": "Some name",
  "statusCode: 500
}
""")
```

It's sort of a net complexity reasoning. We eliminate an alternative decorator syntax, but still add back some contortions to have to special case "" vs """. FWIW, I think the latter is more complex so we still would net more complexity if we do that. But none of the complexity here is so terrible that we couldn't just decide it's worth it or anything.

**Comment by bterlson** [comment]
yeah good point RE: example. Ok, I'm on board with leaving it as we have it.

**Comment by daviwil** [comment]
I didn't realize that parenless decorators were a thing until I looked at petstore.adl yesterday.  I kinda like the way it looks!  Didn't know you could do multiline triple-quote with it, that seems like a pretty good compromise.

I really like the idea of having as little special syntax as possible and leaving all language extensions to decorators.  It's definitely the Lisper in me talking, but I think it will make our lives a lot easier and will keep the core language parser very stable and unchanging over time.

**Comment by nguerrera** [comment]
OK, looks like we have consensus not to dial this back again right. Re-closing. Feel free to reopen if something changes.
