### ISSUE TITLE
Composition reform

### ISSUE THREAD

**Issue by bterlson** [Azure/adl#276]
Implementing the visibility framework proposed in RPaaS requires some careful thought. Today ADL uses `...` to mean, effectively, `extends` - properties from the parent models copied into the child model but preserve their original identity. If we combine this semantics with decorators, we observe the following:

```
model A { x: string }

@makePropertiesOptional
model B { ... A }
```

The only way to make sense of this is that the `makePropertiesReadOnly` decorator can't do anything. It doesn't see any own properties on B, and it can't walk up to A to change those properties because that would be like changing A itself. Probably not what you want.

This has two problems, as I see it: it would be useful to compose objects from other objects and apply decorators to the result - this gives "views". Additionally, the `spread` syntax is really creating a subtype but that is sort of non-obvious from the syntax.

A way to fix this is the following:

## Spread creates new properties

The spread syntax creates new properties in the parent by re-evaluating the properties on the target in the context of the parent. So, the following two declarations are roughly identical:

```
@md model A { @pd x: string }
@md model B { ... A }
```

Note how model B needs the `@md` decorator - `...` peels the properties out of its target, but does nothing with its container. With this we can implement "views" and the visibility framework:

```js
const visibility = new Map();
export function getVisibility(entity) {
  return visibility.get(entity);
}
export function v(c, t, v) {
  visibility.set(t, v);
}

export function wv(c, t, v) {
  const filter = (_, prop) => {
    const vis = getVisibility(prop);
    return vis && vis !== v;
  }

  mapFilterOut(t.properties, filter);
}

function mapFilterOut(map, pred) {
  for (const [key, prop] of map) {
    if (pred(key, prop)) {
      map.delete(key);
    }
  }
}
```

```
model Person {
  @v("read") id: string;
  @v("write") secret: string;
  name: string;
}

@wv("read")
model Readable<T> {
  ... T;
}

@wv("write")
model Writable<T> {
  ... T;
}

@resource("/hello")
interface Hello {
  @get read(@path id: string): Readable<Person>;
  @post create(person: Writable<Person>): Readable<Person>;
}
```

Here we use model templates and decorators together to give us nice Readable and Writable templates. We don't even need to declare the usages which is super handy.

## Introduce `model extends`

Unfortunately, approving the above makes it very difficult to recover the "inheritance hierarchy" when e.g. emitting to OpenAPI with it's `allOf` semantics. So I propose we make extensions explicit using `model extends` syntax:

```
model Person {
  name: string;
}

@childDecorator
model Child extends Person {
  toys: string[];
}
```

In this model, the child decorator sees only the `toys` property. It inherits the `name` property from Person, and cannot modify it or add metadata too it. This means something like this is nonsense:

```
model Person {
  @v('read') id: string;
  name: string;
}

@wv('read')
model Child extends Person {
  toys: string[];
}
```

The `wv` decorator will only see the toys property. The child model will still inherit the full Person model. This could be worked around with a small change to explicitly inherit from the readable version of Person:

```
@wv('read')
model Child extends Readable<Person> {
  toys: string[];
}
```

**Comment by daviwil** [comment]
All sounds good.  I think the recommendation to ADL users should be that they should use `...` in all cases where explicit model type hierarchies are not needed.  I think people will generally gravitate toward `extends` when they see it but it gives them less flexibility than `...`.

**Comment by nguerrera** [comment]
I like it a lot. I felt dirty when I modeled spread as inheritance-like, but it made the swagger output so much nicer on our examples. Having a way to just express this intent and going back to a more intuitive meaning of spread seems like the right call. 
 
Some thoughts:

* I assume multiple inheritance to fully leverage allOf is allowed? Comma separated?

* Assuming yes, same strict rule of no duplicate properties between bases? (I see already that you cannot override in proposal.)

* Right now, I also opportunistically made `A & B` semantically something similar to `[anonymous empty model] extends A, B`, again because there were wins in the swagger gen. Would this need to become a third semantic thing or can it be semantically equivalent to { ...A, ...B } maybe?

**Comment by bterlson** [comment]
> I assume multiple inheritance to fully leverage allOf is allowed? Comma separated?

Yeah I think so.

> Assuming yes, same strict rule of no duplicate properties between bases? 

I can't make sense of duplicates being allowed, so I think it's an error. But I'm open to ideas if it makes sense to allow and can be reasoned about?

> Would [`A & B`] need to become a third semantic thing or can it be semantically equivalent to { ...A, ...B } maybe?

I think it's the latter, yeah. I think it's pretty unexpected that intersecting creates a subclassing relationship.

**Comment by daviwil** [comment]
Yeah I also wouldn't expect `A & B` to be subclassed.

**Comment by bterlson** [comment]
There's a class of undefined behavior in this proposal as it relates to whether and how subtypes can override supertypes. @johanste has some thoughts here.

**Comment by nguerrera** [comment]
> I can't make sense of duplicates being allowed, so I think it's an error. But I'm open to ideas if it makes sense to allow and can be reasoned about?

If possible, I would like it to be an error for as long as we can get away with it. It's a can of worms. 

> There's a class of undefined behavior in this proposal as it relates to whether and how subtypes can override supertypes.

Oh I interpreted this to mean it was defined to be an error:
>It inherits the name property from Person, and cannot modify it or add metadata too it. 

I think allowing overrides is less complex than duplicate inherited properties from bases, but also something I'd disallow if we can get away with it.

**Comment by bterlson** [comment]
It's not super clear, but what I mean is, given a case like:

```
model Person { name: string; }
model Child extends Person { };
```

Child inherits name (its defining a subtype), but it doesn't get the property. A decorator on Child that iterated over its properties wouldn't see `name`. It could presumably walk up to the parent to see a `name` property there, but it couldn't modify it or add metadata to it because doing so would be like modifying the declaration of `Person` - there is no separate inherited property. This contrasts with `...` which duplicates the property identity, giving the new composed type a fresh version for decorators to party with.

I didn't intend to say anything about whether you could declare a same-named property that overrides the supertype. I agree with the instinct to disallow it, but @johanste seems pretty convinced it's required. If we allow it, we'd probably want similar rules around subclassed properties being subtypes of any overridden properties, but so far we haven't had to compute the subtype relationship and I'm not eager to implement that 😂.

**Comment by johanste** [comment]
Awkward example:

```
model Leg { length: int }
model DogLeg extends Leg { claws: str[4] }

model Pet { species: str, legs: Leg[] } // A pet can have an arbitrary number of generic legs
model Dog { species: "dog", legs: DogLeg[4] } // A dog tends to have at most 4 dog legs...
```

**Comment by johanste** [comment]
A special case is (as per above) the discriminator field that has a literal (more constrained - and thus overridden) value in the extended class...

**Comment by bterlson** [comment]
@johanste I think examples from real services would be very helpful if you can dig some up!

**Comment by johanste** [comment]
Form Recognizer. But due to limitations in autorest, we have not been able to describe the service in the most precise way. So the swagger describing the service is wishy-washy on what fields will be returned for the various built-in form types. We are working on updating the swagger to the format that (I think) autorest should support.
